# 3-tier-app Backend (Java Spring Boot)
# Auto-updated by Jenkins CI

backend:
  name: backend
  image:
    repository: devkrishan001/3tier-backend
    tag: "v1"
    pullPolicy: Always
  replicas: 2
  port: 7777
  service:
    type: NodePort
    nodePort: 30090
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuThreshold: 60
  pdb:
    enabled: true
    minAvailable: 1
  env:
    DB_HOST: mysql-service
    DB_PORT: "3306"
namespace: three-tier-app
