# Backend App
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dev-krishan-dhaka/platform-helm-charts
      targetRevision: HEAD
      path: charts/backend-service
      helm:
        valueFiles:
          - $values/dev/user-management/backend-values.yaml
    - repoURL: https://github.com/dev-krishan-dhaka/gitops-environments
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: user-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
---
# Frontend App
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dev-krishan-dhaka/platform-helm-charts
      targetRevision: HEAD
      path: charts/frontend-service
      helm:
        valueFiles:
          - $values/dev/user-management/frontend-values.yaml
    - repoURL: https://github.com/dev-krishan-dhaka/gitops-environments
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: user-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
---
# Postgres App
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dev-krishan-dhaka/platform-helm-charts
      targetRevision: HEAD
      path: charts/postgres
      helm:
        valueFiles:
          - $values/dev/user-management/postgres-values.yaml
    - repoURL: https://github.com/dev-krishan-dhaka/gitops-environments
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: user-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
